spring:
  application:
    name: config-ser
 //Hey I am inside the Microservices branch :)
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defafaultZone: http://localhost:8761/eureka
